use std::env;
use std::ffi::OsStr;
use std::path::{Path, PathBuf};

fn split_file_at_dot(file: &OsStr) -> (&OsStr, Option<&OsStr>) {
    let slice = os_str_as_u8_slice(file);
    if slice == b".." {
        return (file, None);
    }

    // The unsafety here stems from converting between &OsStr and &[u8]
    // and back. This is safe to do because (1) we only look at ASCII
    // contents of the encoding and (2) new &OsStr values are produced
    // only from ASCII-bounded slices of existing &OsStr values.
    let i = match slice[1..].iter().position(|b| *b == b'.') {
        Some(i) => i + 1,
        None => return (file, None),
    };
    let before = &slice[..i];
    let after = &slice[i + 1..];
    unsafe { (u8_slice_as_os_str(before), Some(u8_slice_as_os_str(after))) }
}

fn os_str_as_u8_slice(s: &OsStr) -> &[u8] {
    unsafe { &*(s as *const OsStr as *const [u8]) }
}
unsafe fn u8_slice_as_os_str(s: &[u8]) -> &OsStr {
    // SAFETY: see the comment of `os_str_as_u8_slice`
    unsafe { &*(s as *const [u8] as *const OsStr) }
}

fn my_file_prefix(path: &Path) -> Option<&OsStr> {
    path.file_name()
        .map(split_file_at_dot)
        .and_then(|(before, _after)| Some(before))
}

// from https://github.com/Interstellar-Network/rust-cxx-cmake-bridge/blob/2236064d88a1e72897f77b2ecbeecab3402c4c6d/src/lib.rs
fn parse_lib_name(static_lib_path: &Path) -> String {
    let static_lib_path = Path::new(static_lib_path);

    // NOTE: file_stem only split eg "libprotobufd.so.3.19.4.0" -> "libprotobufd.so.3.19.4"
    // but that is NOT what we want (ie "libprotobufd")
    // TODO use "file_prefix" https://github.com/rust-lang/rust/issues/86319
    let liblib_name = my_file_prefix(static_lib_path).unwrap();
    let liblib_name_str: String = liblib_name.to_str().unwrap().into();
    let lib_name_str = liblib_name_str.strip_prefix("lib").unwrap();

    lib_name_str.to_string()
}

// Parse the content of "cmake_generated_rust_wrapper_libs" which SHOULD have
// been generated by our CMake function.
// It is expected to contain a list of space separated libraries eg:
// "/full/path/build/liblib1.so /full/path/build/liblib2.a /usr/lib/x86_64-linux-gnu/libpng16.so.16.37.0"
// etc
fn emit_link_libs(cmake_generated_rust_wrapper_libs: &[PathBuf]) {
    // Previous version was globing all .a and .so in the build dir but it only worked for SHARED dependencies.
    // That is b/c when linking STATIC libs order matters! So we must get a proper list from CMake.
    for static_lib_path in cmake_generated_rust_wrapper_libs {
        let lib_name = parse_lib_name(static_lib_path);

        // let cargo-3ds and rest of the toolchain to this for us
        // this also frees us from the responsibility to decide whether to link with ctru or with ctrud
        if lib_name == "ctru" {
            continue;
        }

        // we pray that all the libs we need are installed to the common cmake's lib directory or are provided in the system library path
        println!("cargo:rustc-link-lib={}={}", "static", lib_name);
    }
}

fn main() {
    // dkp toolchain handling copied from https://github.com/rust3ds/ctru-rs/blob/786af2bdb43b2f178afc59f4f9d07c410235556f/ctru-sys/build.rs
    let devkitpro = env::var("DEVKITPRO").unwrap();
    let devkitarm = env::var("DEVKITARM").unwrap();

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-env-changed=DEVKITPRO");

    let bin_dir = Path::new(devkitarm.as_str()).join("bin");
    let cc = bin_dir.join("arm-none-eabi-gcc");
    let cpp = bin_dir.join("arm-none-eabi-g++");
    let ar = bin_dir.join("arm-none-eabi-ar");

    let include_path = Path::new(devkitpro.as_str()).join("libctru/include");

    let mut cc_build = cc::Build::new();
    cc_build
        .compiler(cc)
        .archiver(ar)
        .include(&include_path)
        .define("ARM11", None)
        .define("__3DS__", None)
        .flag("-march=armv6k")
        .flag("-mtune=mpcore")
        .flag("-mfloat-abi=hard")
        .flag("-mfpu=vfp")
        .flag("-mtp=soft");
    let mut cpp_build = cc_build.clone();
    cpp_build.compiler(cpp).flag("-fno-rtti");

    // this basically reimplements DevkitArm3DS.cmake toolchain file to make if compose well with C flags that rust wants
    let dst = cmake::Config::new("cpp")
        .define("CMAKE_POLICY_VERSION_MINIMUM", "3.5")
        .define("DEVKITPRO", &devkitpro)
        .define("DEVKITARM", &devkitarm)
        .define("CMAKE_SYSTEM_NAME", "Generic")
        .define("CMAKE_SYSTEM_VERSION", "DKA-3DS-52")
        .define("CMAKE_SYSTEM_PROCESSOR", "armv6k")
        .define(
            "CMAKE_FIND_ROOT_PATH",
            format!("{};{}", devkitpro, devkitarm),
        )
        .define("CMAKE_FIND_ROOT_PATH_MODE_PROGRAM", "NEVER")
        .define("CMAKE_FIND_ROOT_PATH_MODE_LIBRARY", "ONLY")
        .define("CMAKE_FIND_ROOT_PATH_MODE_INCLUDE", "ONLY")
        .define("CMAKE_FIND_ROOT_PATH_MODE_PACKAGE", "ONLY")
        .define("3DS", "TRUE")
        .generator("Ninja")
        .build_target("install")
        .init_c_cfg(cc_build)
        .init_cxx_cfg(cpp_build)
        .very_verbose(true)
        .build();

    let static_lib_list = std::fs::read_to_string(dst.join("build/cmake_generated_libs"))
        .unwrap()
        .split(&[' ', '\n'][..])
        .filter(|&x| !x.is_empty())
        .map(|x| x.into())
        .collect::<Vec<_>>();

    println!(
        "cargo:rustc-link-search=native={}",
        dst.join("lib").display()
    );

    emit_link_libs(&static_lib_list);

    // link to stdc++ because we will be likely linked by gcc, not g++
    println!("cargo:rustc-link-lib=static=stdc++");

    // crash the build.rs to examine its stdout
    // std::process::exit(1);
}
